### ISSUE TITLE
How do I make det_ingrs.json?

### ISSUE THREAD

**Issue by tomoki-oke** [torralba-lab/im2recipe#20]
I'm making my own dataset for trying your model.
I've been made layer1.json and layer2.json.
But I wonder about about det_ingrs.json file.
This file contains id, ingredients and valid.
I suppose that a value valid show whether an ingredients corresponding on its index exists or not in vocab.txt.
Is it correct?
If not, please let me know what det_ingrs.json means and how I make det_ingrs.json.

**Comment by nhynes** [comment]
`valid` refers to whether the ingredient detection has a relatively high probability of being correct. For instance, in the first entry, `(makes about 4 cups)` is correctly marked as `valid=False` since the detection model was uncertain about whether that was an ingredient. If you know for sure the ingredients, then `valid=True` always
